channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - requests
      - flask
      - ollama
      - langchain
      - langchain-community
      - langchain-chroma
      - unstructured
      - chromadb
name: llm_env